apiVersion: v1
kind: Pod
metadata:
  namespace: fernando
  name: backupchfoperator
spec:
  containers:
    - name: backup-operator
      image: hub.docker.hpecorp.net/ctg-did-snapshot/backup_operator
  serviceAccountName: controller-manager
