# permissions for end users to view backupchfoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: backup-project
    app.kubernetes.io/managed-by: kustomize
  name: backupchfoperator-viewer-role
rules:
- apiGroups:
  - backupchfoperator.backup-operator-domain
  resources:
  - backupchfoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backupchfoperator.backup-operator-domain
  resources:
  - backupchfoperators/status
  verbs:
  - get
