# permissions for end users to edit backupchfoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: backup-project
    app.kubernetes.io/managed-by: kustomize
  name: backupchfoperator-editor-role
rules:
- apiGroups:
  - backupchfoperator.backup-operator-domain
  resources:
  - backupchfoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backupchfoperator.backup-operator-domain
  resources:
  - backupchfoperators/status
  verbs:
  - get
